sonar.organization=viniciusalmeidadeavila
sonar.projectKey=viniciusalmeidadeavila_pipeline

sonar.sources=.
sonar.language=js,css,web
sonar.inclusions=/*.js,/.css,**/.html
sonar.exclusions=node_modules/,.github/